# Generated by Django 5.2.7 on 2025-10-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='images/default.svg', upload_to='product_images/'),
        ),
    ]
